version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=expense_db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  frontend_react:
    build: ./frontend_react
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
  
  frontend_flutter:
    build: ./frontend_flutter
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - app-network


volumes:
  pgdata:

networks:
  app-network:
